language: rust
cache: cargo
os:
  - linux
  - osx
env:
  global:
    - BIN=$(echo $TRAVIS_REPO_SLUG | cut -d '/' -f2)
script:
  - echo ${BIN}-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz
before_deploy:
  - cargo build --release
  - cd target/release
  - ls
  - tar -zcvf ${BIN}-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz ${BIN}
  - cd ../..
deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file: target/release/${BIN}-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz
    overwrite: true
    skip_cleanup: true
    on:
      tags: true
